spring:
  datasource:
    url: jdbc:h2:~/springbootcrud
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  redis:
    host: 192.168.77.140
    password: 123456
    port: 6379
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG